# Generated by Django 2.1.3 on 2018-11-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181117_1626'),
        ('members', '0002_auto_20181102_1249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
